apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Mnubo Inventory Sync
  description: Mnubo Device Integration Plugin for the Reekoh IoT Platform. Connects a Reekoh Instance with Mnubo to sync devices.
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: InventorySync
  price: 0
  tags:
    - inventory-sync
    - mnubo

  consumerType: pull
  
  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      clientId:
        label: Client ID
        type: String
        maxLength: 1000
        required: true
        help: "Your Mnubo Client ID."
      clientSecret:
        label: Client Secret
        type: Password
        maxLength: 1000
        required: true
        help: "Your Mnubo Client Secret."
      env:
        label: Environment
        type: String
        maxLength: 1000
        required: true
        enum:
          - sandbox
          - production
        help: "Your Mnubo environment."